#!/usr/bin/env python3
"""Post-build: write redirect stubs for the old Sphinx URLs into the MyST HTML build.

Sphinx served every page at <path>.html (e.g. technical_tutorials/search/catalog.html);
MyST serves it at /technical-tutorials/search/catalog/. mystmd has no redirect feature,
so for every old page a small HTML file is written at the old path that redirects to
the new one, translating an nbsphinx-style #Heading-Anchor into the mystmd id form.
The mapping comes from migration/redirect_map.json (committed, generated by migrate.py).

Usage: python migration/gen_redirects.py [--html docs/source/_build/html]
Runs on ReadTheDocs after `myst build --html` (see .readthedocs.yml).
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
DEFAULT_HTML = HERE.parent / "docs" / "source" / "_build" / "html"

TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Redirecting…</title>
<link rel="canonical" href="{target}">
<meta http-equiv="refresh" content="0; url={target}">
<script>
(function () {{
  // nbsphinx anchors looked like #Title-Case-(Parens); mystmd ids are lowercase slugs.
  var h = decodeURIComponent(location.hash.slice(1));
  if (h) {{
    h = h.replace(/[\\t\\n\\r ]+/g, " ").replace(/['\\u2018\\u2019"\\u201c\\u201d]+/g, "").trim().toLowerCase()
         .replace(/[^a-z0-9-]/g, "-").replace(/^([0-9-])/, "id-$1").replace(/-[-]+/g, "-").replace(/(?:^[-]+)|(?:[-]+$)/g, "");
  }}
  location.replace("{target}" + (h ? "#" + h : ""));
}})();
</script>
</head>
<body>
<p>This page has moved to <a href="{target}">{target}</a>.</p>
</body>
</html>
"""


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--html", type=Path, default=DEFAULT_HTML)
    args = ap.parse_args()
    html = args.html.resolve()
    if not (html / "index.html").exists():
        print(f"ERROR: {html}/index.html not found; run `myst build --html` first", file=sys.stderr)
        return 1
    mapping = json.loads((HERE / "redirect_map.json").read_text())
    written = skipped = 0
    for old, new in sorted(mapping.items()):
        if new == "/" and old == "index.html":
            continue                                   # root stays index.html
        depth = old.count("/")
        # relative target so the stub works under any prefix (e.g. RTD's /en/latest/)
        target = ("../" * depth if depth else "./") + new.lstrip("/")
        dest = html / old
        new_dir = html / new.strip("/")
        if not (new_dir / "index.html").exists():
            print(f"ERROR: new page missing for {old} -> {new}", file=sys.stderr)
            return 1
        if dest.exists():
            print(f"ERROR: refusing to overwrite existing {dest}", file=sys.stderr)
            return 1
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(TEMPLATE.format(target=target), encoding="utf-8")
        written += 1
    print(f"[gen_redirects] wrote {written} redirect stubs into {html} ({skipped} skipped)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
