"""Step 5: write docs/source/myst.yml (generated toc) and the site CSS."""
from __future__ import annotations

from pathlib import Path

import yaml

MYST_YML_HEADER = """\
# MyST configuration for the MAAP User Documentation.
# GENERATED by migration/migrate.py (project.toc mirrors the former Sphinx toctrees).
# Hand-edit freely after the migration has been merged; until then re-run the migration.
# Reference: https://mystmd.org/guide/frontmatter and https://mystmd.org/guide/table-of-contents
"""

CUSTOM_CSS = """\
/* Site CSS for the MyST build (site.options.style in myst.yml). */

/* Isolated (iframe) notebook outputs, e.g. R htmlwidgets/Leaflet maps, span the
   content column as they did under nbsphinx. Without this the browser default
   iframe width of 300px applies. See migration/agent-docs/03-spike-results.md. */
iframe.jp-mod-isolated {
  width: 100%;
}
"""


def run(ctx) -> None:
    src: Path = ctx.src
    config = {
        "version": 1,
        "project": {
            "title": "MAAP User Documentation",
            "github": "https://github.com/MAAP-Project/maap-documentation",
            "copyright": "2020-2026, NASA MAAP Team",
            "toc": ctx.toc,
            "exclude": ["**/.ipynb_checkpoints/**", "_build/**"],
            "settings": {
                # nbsphinx showed every text/plain output; mystmd's default hides matplotlib-style reprs
                "output_matplotlib_strings": "show",
            },
        },
        "site": {
            "template": "book-theme",
            "options": {
                "folders": True,
                "logo": "_static/nasamaap_logo.png",
                "favicon": "_static/maapsheep-80x80.png",
                "style": "_static/custom.css",
            },
        },
    }
    text = MYST_YML_HEADER + yaml.safe_dump(config, sort_keys=False, allow_unicode=True, width=120)
    (src / "myst.yml").write_text(text, encoding="utf-8")
    (src / "_static" / "custom.css").write_text(CUSTOM_CSS, encoding="utf-8")
    print("[write_config] wrote myst.yml and _static/custom.css")
